# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactNativeApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeApp
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'

  target 'reactNativeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeApp-tvOS

  target 'reactNativeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
